// Built-in fallback: MiniMax system voices for English, Mandarin, Cantonese and Japanese,
// as [voice ID, voice name] from https://platform.minimax.io/docs/faq/system-voice-id.
// With a key, Canary loads the account's full list from the Get Voice API instead.
export const BUILT_IN_SYSTEM_VOICES = Object.freeze({
    English: [
        ['English_expressive_narrator', 'Expressive Narrator'],
        ['English_radiant_girl', 'Radiant Girl'],
        ['English_magnetic_voiced_man', 'Magnetic-voiced Male'],
        ['English_compelling_lady1', 'Compelling Lady'],
        ['English_Aussie_Bloke', 'Aussie Bloke'],
        ['English_captivating_female1', 'Captivating Female'],
        ['English_Upbeat_Woman', 'Upbeat Woman'],
        ['English_Trustworth_Man', 'Trustworthy Man'],
        ['English_CalmWoman', 'Calm Woman'],
        ['English_UpsetGirl', 'Upset Girl'],
        ['English_Gentle-voiced_man', 'Gentle-voiced Man'],
        ['English_Whispering_girl', 'Whispering girl'],
        ['English_Diligent_Man', 'Diligent Man'],
        ['English_Graceful_Lady', 'Graceful Lady'],
        ['English_ReservedYoungMan', 'Reserved Young Man'],
        ['English_PlayfulGirl', 'Playful Girl'],
        ['English_ManWithDeepVoice', 'Man With Deep Voice'],
        ['English_MaturePartner', 'Mature Partner'],
        ['English_FriendlyPerson', 'Friendly Guy'],
        ['English_MatureBoss', 'Bossy Lady'],
        ['English_Debator', 'Male Debater'],
        ['English_LovelyGirl', 'Lovely Girl'],
        ['English_Steadymentor', 'Reliable Man'],
        ['English_Deep-VoicedGentleman', 'Deep-voiced Gentleman'],
        ['English_Wiselady', 'Wise Lady'],
        ['English_CaptivatingStoryteller', 'Captivating Storyteller'],
        ['English_DecentYoungMan', 'Decent Young Man'],
        ['English_SentimentalLady', 'Sentimental Lady'],
        ['English_ImposingManner', 'Imposing Queen'],
        ['English_SadTeen', 'Teen Boy'],
        ['English_PassionateWarrior', 'Passionate Warrior'],
        ['English_WiseScholar', 'Wise Scholar'],
        ['English_Soft-spokenGirl', 'Soft-Spoken Girl'],
        ['English_SereneWoman', 'Serene Woman'],
        ['English_ConfidentWoman', 'Confident Woman'],
        ['English_PatientMan', 'Patient Man'],
        ['English_Comedian', 'Comedian'],
        ['English_BossyLeader', 'Bossy Leader'],
        ['English_Strong-WilledBoy', 'Strong-Willed Boy'],
        ['English_StressedLady', 'Stressed Lady'],
        ['English_AssertiveQueen', 'Assertive Queen'],
        ['English_AnimeCharacter', 'Female Narrator'],
        ['English_Jovialman', 'Jovial Man'],
        ['English_WhimsicalGirl', 'Whimsical Girl'],
        ['English_Kind-heartedGirl', 'Kind-Hearted Girl'],
    ],
    'Chinese (Mandarin)': [
        ['Chinese (Mandarin)_Reliable_Executive', 'Reliable Executive'],
        ['Chinese (Mandarin)_News_Anchor', 'News Anchor'],
        ['Chinese (Mandarin)_Unrestrained_Young_Man', 'Unrestrained Young Man'],
        ['Chinese (Mandarin)_Mature_Woman', 'Mature Woman'],
        ['Arrogant_Miss', 'Arrogant Miss'],
        ['Robot_Armor', 'Robot Armor'],
        ['Chinese (Mandarin)_Kind-hearted_Antie', 'Kind-hearted Antie'],
        ['Chinese (Mandarin)_HK_Flight_Attendant', 'HK Flight Attendant'],
        ['Chinese (Mandarin)_Humorous_Elder', 'Humorous Elder'],
        ['Chinese (Mandarin)_Gentleman', 'Gentleman'],
        ['Chinese (Mandarin)_Warm_Bestie', 'Warm Bestie'],
        ['Chinese (Mandarin)_Stubborn_Friend', 'Stubborn Friend'],
        ['Chinese (Mandarin)_Sweet_Lady', 'Sweet Lady'],
        ['Chinese (Mandarin)_Southern_Young_Man', 'Southern Young Man'],
        ['Chinese (Mandarin)_Wise_Women', 'Wise Women'],
        ['Chinese (Mandarin)_Gentle_Youth', 'Gentle Youth'],
        ['Chinese (Mandarin)_Warm_Girl', 'Warm Girl'],
        ['Chinese (Mandarin)_Male_Announcer', 'Male Announcer'],
        ['Chinese (Mandarin)_Kind-hearted_Elder', 'Kind-hearted Elder'],
        ['Chinese (Mandarin)_Cute_Spirit', 'Cute Spirit'],
        ['Chinese (Mandarin)_Radio_Host', 'Radio Host'],
        ['Chinese (Mandarin)_Lyrical_Voice', 'Lyrical Voice'],
        ['Chinese (Mandarin)_Straightforward_Boy', 'Straightforward Boy'],
        ['Chinese (Mandarin)_Sincere_Adult', 'Sincere Adult'],
        ['Chinese (Mandarin)_Gentle_Senior', 'Gentle Senior'],
        ['Chinese (Mandarin)_Crisp_Girl', 'Crisp Girl'],
        ['Chinese (Mandarin)_Pure-hearted_Boy', 'Pure-hearted Boy'],
        ['Chinese (Mandarin)_Soft_Girl', 'Soft Girl'],
        ['Chinese (Mandarin)_IntellectualGirl', 'Intellectual Girl'],
        ['Chinese (Mandarin)_Warm_HeartedGirl', 'Warm-hearted Girl'],
        ['Chinese (Mandarin)_Laid_BackGirl', 'Laid-back Girl'],
        ['Chinese (Mandarin)_ExplorativeGirl', 'Explorative Girl'],
        ['Chinese (Mandarin)_Warm-HeartedAunt', 'Warm-hearted Aunt'],
        ['Chinese (Mandarin)_BashfulGirl', 'Bashful Girl'],
    ],
    Cantonese: [
        ['Cantonese_ProfessionalHost (F)', 'Professional Female Host'],
        ['Cantonese_GentleLady', 'Gentle Lady'],
        ['Cantonese_ProfessionalHost (M)', 'Professional Male Host'],
        ['Cantonese_PlayfulMan', 'Playful Man'],
        ['Cantonese_CuteGirl', 'Cute Girl'],
        ['Cantonese_KindWoman', 'Kind Woman'],
    ],
    Japanese: [
        ['Japanese_IntellectualSenior', 'Intellectual Senior'],
        ['Japanese_DecisivePrincess', 'Decisive Princess'],
        ['Japanese_LoyalKnight', 'Loyal Knight'],
        ['Japanese_DominantMan', 'Dominant Man'],
        ['Japanese_SeriousCommander', 'Serious Commander'],
        ['Japanese_ColdQueen', 'Cold Queen'],
        ['Japanese_DependableWoman', 'Dependable Woman'],
        ['Japanese_GentleButler', 'Gentle Butler'],
        ['Japanese_KindLady', 'Kind Lady'],
        ['Japanese_CalmLady', 'Calm Lady'],
        ['Japanese_OptimisticYouth', 'Optimistic Youth'],
        ['Japanese_GenerousIzakayaOwner', 'Generous Izakaya Owner'],
        ['Japanese_SportyStudent', 'Sporty Student'],
        ['Japanese_InnocentBoy', 'Innocent Boy'],
        ['Japanese_GracefulMaiden', 'Graceful Maiden'],
    ],
});
