// Built-in fallback: MiniMax system voices for English, Mandarin, Cantonese and Japanese,
// from https://platform.minimax.io/docs/faq/system-voice-id. With a key, Canary loads the
// account's full list (all languages plus cloned voices) from the Get Voice API instead.
export const BUILT_IN_VOICE_IDS = Object.freeze({
    English: [
        'English_expressive_narrator', 'English_radiant_girl', 'English_magnetic_voiced_man',
        'English_compelling_lady1', 'English_Aussie_Bloke', 'English_captivating_female1',
        'English_Upbeat_Woman', 'English_Trustworth_Man', 'English_CalmWoman', 'English_UpsetGirl',
        'English_Gentle-voiced_man', 'English_Whispering_girl', 'English_Diligent_Man',
        'English_Graceful_Lady', 'English_ReservedYoungMan', 'English_PlayfulGirl',
        'English_ManWithDeepVoice', 'English_MaturePartner', 'English_FriendlyPerson',
        'English_MatureBoss', 'English_Debator', 'English_LovelyGirl', 'English_Steadymentor',
        'English_Deep-VoicedGentleman', 'English_Wiselady', 'English_CaptivatingStoryteller',
        'English_DecentYoungMan', 'English_SentimentalLady', 'English_ImposingManner',
        'English_SadTeen', 'English_PassionateWarrior', 'English_WiseScholar',
        'English_Soft-spokenGirl', 'English_SereneWoman', 'English_ConfidentWoman',
        'English_PatientMan', 'English_Comedian', 'English_BossyLeader', 'English_Strong-WilledBoy',
        'English_StressedLady', 'English_AssertiveQueen', 'English_AnimeCharacter',
        'English_Jovialman', 'English_WhimsicalGirl', 'English_Kind-heartedGirl',
    ],
    'Chinese (Mandarin)': [
        'Chinese (Mandarin)_Reliable_Executive', 'Chinese (Mandarin)_News_Anchor',
        'Chinese (Mandarin)_Unrestrained_Young_Man', 'Chinese (Mandarin)_Mature_Woman',
        'Arrogant_Miss', 'Robot_Armor', 'Chinese (Mandarin)_Kind-hearted_Antie',
        'Chinese (Mandarin)_HK_Flight_Attendant', 'Chinese (Mandarin)_Humorous_Elder',
        'Chinese (Mandarin)_Gentleman', 'Chinese (Mandarin)_Warm_Bestie',
        'Chinese (Mandarin)_Stubborn_Friend', 'Chinese (Mandarin)_Sweet_Lady',
        'Chinese (Mandarin)_Southern_Young_Man', 'Chinese (Mandarin)_Wise_Women',
        'Chinese (Mandarin)_Gentle_Youth', 'Chinese (Mandarin)_Warm_Girl',
        'Chinese (Mandarin)_Male_Announcer', 'Chinese (Mandarin)_Kind-hearted_Elder',
        'Chinese (Mandarin)_Cute_Spirit', 'Chinese (Mandarin)_Radio_Host',
        'Chinese (Mandarin)_Lyrical_Voice', 'Chinese (Mandarin)_Straightforward_Boy',
        'Chinese (Mandarin)_Sincere_Adult', 'Chinese (Mandarin)_Gentle_Senior',
        'Chinese (Mandarin)_Crisp_Girl', 'Chinese (Mandarin)_Pure-hearted_Boy',
        'Chinese (Mandarin)_Soft_Girl', 'Chinese (Mandarin)_IntellectualGirl',
        'Chinese (Mandarin)_Warm_HeartedGirl', 'Chinese (Mandarin)_Laid_BackGirl',
        'Chinese (Mandarin)_ExplorativeGirl', 'Chinese (Mandarin)_Warm-HeartedAunt',
        'Chinese (Mandarin)_BashfulGirl',
    ],
    Cantonese: [
        'Cantonese_ProfessionalHost (F)', 'Cantonese_GentleLady', 'Cantonese_ProfessionalHost (M)',
        'Cantonese_PlayfulMan', 'Cantonese_CuteGirl', 'Cantonese_KindWoman',
    ],
    Japanese: [
        'Japanese_IntellectualSenior', 'Japanese_DecisivePrincess', 'Japanese_LoyalKnight',
        'Japanese_DominantMan', 'Japanese_SeriousCommander', 'Japanese_ColdQueen',
        'Japanese_DependableWoman', 'Japanese_GentleButler', 'Japanese_KindLady',
        'Japanese_CalmLady', 'Japanese_OptimisticYouth', 'Japanese_GenerousIzakayaOwner',
        'Japanese_SportyStudent', 'Japanese_InnocentBoy', 'Japanese_GracefulMaiden',
    ],
});
